# Generated by Django 5.2.3 on 2025-06-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_meteo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['-created_at']},
        ),
    ]
