# Generated by Django 5.2.3 on 2025-06-14 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_meteo_api', '0002_alter_alert_options_alter_temperature_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, null=True, unique=True, verbose_name='Cidade')),
            ],
        ),
        migrations.RemoveField(
            model_name='alert',
            name='sent',
        ),
        migrations.AddField(
            model_name='alert',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='alert',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='alert',
            name='operator',
            field=models.CharField(choices=[('=', 'Igual a'), ('>', 'Maior que'), ('<', 'Menor que')], default='=', max_length=1, verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='alert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='temperature',
            field=models.FloatField(verbose_name='Temperatura'),
        ),
        migrations.AddField(
            model_name='alert',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='open_meteo_api.city', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_meteo_api.city', verbose_name='Cidade'),
        ),
    ]
