# Generated by Django 5.2.3 on 2025-06-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_meteo_api', '0003_city_remove_alert_sent_alert_active_alert_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
    ]
